### ISSUE TITLE
Uncaught Error: Cannot find module '_process'

### ISSUE THREAD

**Issue by peacemakr** [primus/primus#519]
**Version:**
6.0.6
engine.io: 1.8.2
**Environment:**
  - **Operating system:**
MacOSX
  - **Browser:**
Chrome
  - **Node.js:**
5.12.0

**Expected result:**
Client should load in browser without any issues

**Actual result:**
Getting errors in browser console 
```
primus.js:3529 Uncaught Error: Cannot find module '_process'(…)
```
The client library is served by Primus 
```
<script type="text/javascript" src="/primus/primus.js" ></script>	
```
I also see the following message on client console:
```
Uncaught (in promise) Error: Missing required `engine.io-client` module. Please run `npm install --save engine.io-client`(…)   Line 3183

if (!factory) return primus.critical(new Error(  //<--3183
```
I've already run npm install --save engine.io-client on server side and inside node_modules/primus/ and restarted server

**Steps to reproduce:**
Just upgraded to 6.0.6 and engine.io to 1.8.2

**Comment by peacemakr** [comment]
I'm using uws as transport
	  , transport:    { wsEngine: 'uws' }

**Comment by peacemakr** [comment]
I cleared up all modules, npm cache etc and installed all modules again but same error

**Comment by lpinca** [comment]
I can reproduce the issue. It seems that something changed in `engine.io-client@>=1.8.0`.
As a quick workaround you can use `primus@6.0.5`.

**Comment by lpinca** [comment]
The issue has been introduced with https://github.com/socketio/engine.io-client/pull/520.

In https://github.com/primus/primus/commit/f790c8ee339580d3808f0e4d718f0a46b875f625 I've added a browserify transform to remove all `debug` occurrences from the Engine.IO client and excluded `debug` from the bundle. This also helps reducing the library size.

Thanks for reporting.

**Comment by peacemakr** [comment]
FYI: I used 6.0.7 without this issue
