### ISSUE TITLE
Breaking change in v7.1.1

### ISSUE THREAD

**Issue by daffl** [primus/primus#630]
We are using `primus.setMaxListeners` in the [@featherjs/primus adapter](https://github.com/feathersjs/primus/blob/5ac79d31c2b9f2a47965a8fe5d74c3c4c832dce5/lib/index.js#L67). It appears to have been removed in version 7.1.1 (working in 7.1.0), most likely due to a major update in the eventemitter package in https://github.com/primus/primus/commit/90cc22d313794f2b4449c17b449fb5ed01c0f5e6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

**Version:**

7.1.1

**Environment:**
  - **Operating system:** MacOS
  - **Browser:** -
  - **Node.js:** 8

**Expected result:**

`primus.setMaxListener` should be available

**Actual result:**

Error that it is not a function

**Steps to reproduce:**

Install v7.1.1 and call `primus.setMaxListeners(64);`

**Comment by daffl** [comment]
I'm assuming `primus.setMaxListeners(64);` can just be removed since the new one does not check for leaks.

**Comment by 3rd-Eden** [comment]
Interesting. But yes, setMaxListeners can just be gone, it never worked or was never supported as it was just an empty function. But we shouldn't be breaking patch releases.

**Comment by 3rd-Eden** [comment]
@lpinca Do we want to rollback the EE change and do a v8 bump instead?

**Comment by lpinca** [comment]
I'd just revert https://github.com/primus/primus/pull/622 and cut 7.1.2. Sorry about this.

P.S.  In eventemitter3 `setMaxListeners` has always been a noop.

**Comment by lpinca** [comment]
@3rd-Eden should we revert or ignore this? I think less than 1% of projects using Primus calls `EventEmitter#setMaxListeners()`. Again, sorry for the unwanted breaking change.

**Comment by daffl** [comment]
In npm download numbers this affected probably around 15% of the total Primus downloads so I figured I'd point it out. I fixed it yesterday so either way works for me.

**Comment by lpinca** [comment]
@daffl Thank you for reporting.
